# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitacora < Formula
  desc "Ship's log for AI agents. Persistent memory that survives between sessions."
  homepage "https://github.com/florelmx/bitacora"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/florelmx/bitacora/releases/download/v0.5.0/bitacora_darwin_amd64.tar.gz"
      sha256 "fc34b3391e073c39bbb546bd5f294da960bdc2cfd9c1dcd35d311b841eb29997"

      define_method(:install) do
        bin.install "bitacora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/florelmx/bitacora/releases/download/v0.5.0/bitacora_darwin_arm64.tar.gz"
      sha256 "82f4475ff75d7b374cfd87722349a18e6e4da8852225476cfa970bf12ebd7c0d"

      define_method(:install) do
        bin.install "bitacora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/florelmx/bitacora/releases/download/v0.5.0/bitacora_linux_amd64.tar.gz"
      sha256 "71fcf0f23773de55224b01862b2f40288de7b09b081b4f430fdef7be15076cf1"
      define_method(:install) do
        bin.install "bitacora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/florelmx/bitacora/releases/download/v0.5.0/bitacora_linux_arm64.tar.gz"
      sha256 "3c5179da2925cb10bf76dd9deb932496229376ca73a24828b1f06864b8abb86c"
      define_method(:install) do
        bin.install "bitacora"
      end
    end
  end
end
