# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitacora < Formula
  desc "Ship's log for AI agents. Persistent memory that survives between sessions."
  homepage "https://github.com/florelmx/bitacora"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/florelmx/bitacora/releases/download/v1.0.0/bitacora_darwin_amd64.tar.gz"
      sha256 "2aca094b184e3614da9ab43a4d2891970d7911cb9bea54f31218c2f1a50e19ac"

      define_method(:install) do
        bin.install "bitacora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/florelmx/bitacora/releases/download/v1.0.0/bitacora_darwin_arm64.tar.gz"
      sha256 "afcc8b4719f8d856d266917226370492e9c7305e1d213ca146c31e679624bb7d"

      define_method(:install) do
        bin.install "bitacora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/florelmx/bitacora/releases/download/v1.0.0/bitacora_linux_amd64.tar.gz"
      sha256 "f221f30ad39919b74deda2b8446fbb87de5d72b811f26855b61d23e68eb07c74"
      define_method(:install) do
        bin.install "bitacora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/florelmx/bitacora/releases/download/v1.0.0/bitacora_linux_arm64.tar.gz"
      sha256 "903473af58c89d9a9ba6362295aaf679b9c0b0926528abe840204d917f2be4c6"
      define_method(:install) do
        bin.install "bitacora"
      end
    end
  end
end
